QBShared = QBShared or {}
QBShared.Vehicles = {
	--- Compacts
		['asbo'] = {
		['name'] = 'Asbo',
		['brand'] = 'Maxwell',
		['model'] = 'asbo',
		['price'] = 4000,
		['category'] = 'compacts',
		['hash'] = `asbo`,
		['shop'] = 'pdm',
	},
	['blista'] = {
		['name'] = 'Blista',
		['brand'] = 'Dinka',
		['model'] = 'blista',
		['price'] = 13000,
		['category'] = 'compacts',
		['hash'] = `blista`,
		['shop'] = 'pdm',
	},
	['brioso'] = {
		['name'] = 'Brioso R/A',
		['brand'] = 'Grotti',
		['model'] = 'brioso',
		['price'] = 20000,
		['category'] = 'compacts',
		['hash'] = `brioso`,
		['shop'] = 'pdm',
	},
	['club'] = {
		['name'] = 'Club',
		['brand'] = 'BF',
		['model'] = 'club',
		['price'] = 8000,
		['category'] = 'compacts',
		['hash'] = `club`,
		['shop'] = 'pdm',
	},
	['dilettante'] = {
		['name'] = 'Dilettante',
		['brand'] = 'Karin',
		['model'] = 'dilettante',
		['price'] = 9000,
		['category'] = 'compacts',
		['hash'] = `dilettante`,
		['shop'] = 'pdm',
	},
	['dilettante2'] = {
		['name'] = 'Dilettante Patrol',
		['brand'] = 'Karin',
		['model'] = 'dilettante2',
		['price'] = 12000,
		['category'] = 'compacts',
		['hash'] = `dilettante2`,
		['shop'] = 'pdm',
	},
	['kanjo'] = {
		['name'] = 'Blista Kanjo',
		['brand'] = 'Dinka',
		['model'] = 'kanjo',
		['price'] = 12000,
		['category'] = 'compacts',
		['hash'] = `kanjo`,
		['shop'] = 'pdm',
	},
	['rmodmk7'] = {
		['name'] = 'Volkswagen Golf MK7 Pandem',
		['brand'] = 'Volkswagen',
		['model'] = 'rmodmk7',
		['price'] = 32000,
		['category'] = 'compacts',
		['hash'] = `rmodmk7`,
		['shop'] = 'pdm',
	},
	['celica'] = {
		['name'] = '98 Toyota Celica',
		['brand'] = 'Toyota',
		['model'] = 'celica',
		['price'] = 2900,
		['category'] = 'compacts',
		['hash'] = `celica`,
		['shop'] = 'pdm',
	},

	
	--- Coupes
	['cogcabrio'] = {
		['name'] = 'Cognoscenti Cabrio',
		['brand'] = 'Enus',
		['model'] = 'cogcabrio',
		['price'] = 30000,
		['category'] = 'coupes',
		['hash'] = `cogcabrio`,
		['shop'] = 'pdm',
	},
	['m3e36'] = {
		['name'] = '1997 BMW M3 E36',
		['brand'] = 'BMW',
		['model'] = 'm3e36',
		['price'] = 49700,
		['category'] = 'coupes',
		['hash'] = `m3e36`,
		['shop'] = 'pdm',
	},
	['tdf'] = {
		['name'] = 'Ferrari 2016 F12',
		['brand'] = 'Ferrari',
		['model'] = 'tdf',
		['price'] = 312000,
		['category'] = 'coupes',
		['hash'] = `tdf`,
		['shop'] = 'pdm',
	},
	['dukes'] = {
		['name'] = 'Dodge Charger RT 1970',
		['brand'] = 'Dodge',
		['model'] = 'dukes',
		['price'] = 45000,
		['category'] = 'coupes',
		['hash'] = `dukes`,
		['shop'] = 'pdm',
	},
	['ss69'] = {
		['name'] = 'Cevrolet Camaro 1969',
		['brand'] = 'Cevrolet',
		['model'] = 'ss69',
		['price'] = 9000,
		['category'] = 'coupes',
		['hash'] = `ss69`,
		['shop'] = 'pdm',
	},
	['350zrb'] = {
		['name'] = '2008 Nissan 350 RB',
		['brand'] = 'Nissan',
		['model'] = '350zrb',
		['price'] = 50000,
		['category'] = 'coupes',
		['hash'] = `350zrb`,
		['shop'] = 'pdm',
	},
	['63lb'] = {
		['name'] = 'Mercedes C63 Widebody AMG Coupe',
		['brand'] = 'Mercedes',
		['model'] = '63lb',
		['price'] = 78250,
		['category'] = 'coupes',
		['hash'] = `63lb`,
		['shop'] = 'pdm',
	},
	['w204amgc'] = {
		['name'] = 'Mercedes C63 AMG Coupe',
		['brand'] = 'Mercedes',
		['model'] = 'w204amgc',
		['price'] = 71000,
		['category'] = 'coupes',
		['hash'] = `w204amgc`,
		['shop'] = 'pdm',
	},
	['rx8r'] = {
		['name'] = '2011 Mazda RX-8',
		['brand'] = 'Mazda',
		['model'] = 'rx8r',
		['price'] = 38000,
		['category'] = 'coupes',
		['hash'] = `rx8r`,
		['shop'] = 'pdm',
	},
	
	
	--- Cycles
	['bmx'] = {
		['name'] = 'BMX',
		['model'] = 'bmx',
		['price'] = 160,
		['category'] = 'cycles',
		['hash'] = `bmx`,
		['shop'] = 'pdm',
	},
	['cruiser'] = {
		['name'] = 'Cruiser',
		['model'] = 'cruiser',
		['price'] = 510,
		['category'] = 'cycles',
		['hash'] = `cruiser`,
		['shop'] = 'pdm',
	},
	['fixter'] = {
		['name'] = 'Fixter',
		['model'] = 'fixter',
		['price'] = 225,
		['category'] = 'cycles',
		['hash'] = `fixter`,
		['shop'] = 'pdm',
	},
	['scorcher'] = {
		['name'] = 'Scorcher',
		['model'] = 'scorcher',
		['price'] = 280,
		['category'] = 'cycles',
		['hash'] = `scorcher`,
		['shop'] = 'pdm',
	},
	['tribike'] = {
		['name'] = 'Tri Bike',
		['model'] = 'tribike',
		['price'] = 500,
		['category'] = 'cycles',
		['hash'] = `tribike`,
		['shop'] = 'pdm',
	},
	['tribike2'] = {
		['name'] = 'Tri Bike 2',
		['model'] = 'tribike2',
		['price'] = 700,
		['category'] = 'cycles',
		['hash'] = `tribike2`,
		['shop'] = 'pdm',
	},
	['tribike3'] = {
		['name'] = 'Tri Bike 3',
		['model'] = 'tribike3',
		['price'] = 520,
		['category'] = 'cycles',
		['hash'] = `tribike3`,
		['shop'] = 'pdm',
	},
	--- Motorcycles
	['akuma'] = {
		['name'] = 'Akuma',
		['brand'] = 'Dinka',
		['model'] = 'akuma',
		['price'] = 55000,
		['category'] = 'motorcycles',
		['hash'] = `akuma`,
		['shop'] = 'pdm',
	},
	['avarus'] = {
		['name'] = 'Avarus',
		['brand'] = 'LCC',
		['model'] = 'avarus',
		['price'] = 4500,
		['category'] = 'motorcycles',
		['hash'] = `avarus`,
		['shop'] = 'pdm',
	},
	['HDIron883'] = {
		['name'] = '2017 Harley Sportster',
		['brand'] = 'Harley Davidson',
		['model'] = 'HDIron883',
		['price'] = 35000,
		['category'] = 'motorcycles',
		['hash'] = `HDIron883`,
		['shop'] = 'pdm',
	},
	['dv4r'] = {
		['name'] = 'Ducati Paniagle V4R 2019',
		['brand'] = 'Ducati',
		['model'] = 'dv4r',
		['price'] = 35000,
		['category'] = 'motorcycles',
		['hash'] = `dv4r`,
		['shop'] = 'pdm',
	},
	['06sx2t'] = {
		['name'] = 'KTM 125 SX DirtBike',
		['brand'] = 'KTM',
		['model'] = '06sx2t',
		['price'] = 21000,
		['category'] = 'motorcycles',
		['hash'] = `06sx2t`,
		['shop'] = 'pdm',
	},
	['faggio'] = {
		['name'] = 'Faggio Sport',
		['brand'] = 'Pegassi',
		['model'] = 'faggio',
		['price'] = 500,
		['category'] = 'motorcycles',
		['hash'] = `faggio`,
		['shop'] = 'pdm',
	},
	['faggio2'] = {
		['name'] = 'Faggio',
		['brand'] = 'Pegassi',
		['model'] = 'faggio2',
		['price'] = 750,
		['category'] = 'motorcycles',
		['hash'] = `faggio2`,
		['shop'] = 'pdm',
	},
	['faggio3'] = {
		['name'] = 'Faggio Mod',
		['brand'] = 'Pegassi',
		['model'] = 'faggio3',
		['price'] = 1000,
		['category'] = 'motorcycles',
		['hash'] = `faggio3`,
		['shop'] = 'pdm',
	},
	
	--- Muscle
	['blade'] = {
		['name'] = 'Blade',
		['brand'] = 'Vapid',
		['model'] = 'blade',
		['price'] = 23500,
		['category'] = 'muscle',
		['hash'] = `blade`,
		['shop'] = 'pdm',
	},
	['16challenger'] = {
		['name'] = '2016 Dodge Challenger Hemi',
		['brand'] = 'Dodge',
		['model'] = '16challenger',
		['price'] = 77900,
		['category'] = 'muscle',
		['hash'] = `16challenger`,
		['shop'] = 'pdm',
	},
	['dcd'] = {
		['name'] = '2020 Dodge Challenger Demon',
		['brand'] = 'Dodge',
		['model'] = 'dcd',
		['price'] = 95500,
		['category'] = 'muscle',
		['hash'] = `dcd`,
		['shop'] = 'pdm',
	},
	['rmodmustang'] = {
		['name'] = '2018 302 Boss Mustang RMOD',
		['brand'] = 'Ford',
		['model'] = 'rmodmustang',
		['price'] = 90500,
		['category'] = 'muscle',
		['hash'] = `rmodmustang`,
		['shop'] = 'pdm',
	},
	['rtr'] = {
		['name'] = '2019 Ford Mustang RTR Drag',
		['brand'] = 'Ford',
		['model'] = 'rtr',
		['price'] = 99500,
		['category'] = 'muscle',
		['hash'] = `rtr`,
		['shop'] = 'pdm',
	},
	['rmodzl1'] = {
		['name'] = 'Chevy Camaro ZL1 Widebody',
		['brand'] = 'Chevrolet',
		['model'] = 'rmodzl1',
		['price'] = 71500,
		['category'] = 'muscle',
		['hash'] = `rmodzl1`,
		['shop'] = 'pdm',
	},
	['sjdodge'] = {
		['name'] = 'Dodge Charger 2021',
		['brand'] = 'Dodge',
		['model'] = 'sjdodge',
		['price'] = 71500,
		['category'] = 'muscle',
		['hash'] = `sjdodge`,
		['shop'] = 'pdm',
	},
	['c7'] = {
		['name'] = '2015 Corvette C7',
		['brand'] = 'Dodge',
		['model'] = 'c7',
		['price'] = 61200,
		['category'] = 'muscle',
		['hash'] = `c7`,
		['shop'] = 'pdm',
	},
	['exor'] = {
		['name'] = 'Chevrolet Camaro Exorcist',
		['brand'] = 'Chevrolet',
		['model'] = 'exor',
		['price'] = 93000,
		['category'] = 'muscle',
		['hash'] = `exor`,
		['shop'] = 'pdm',
	},
	['firebird'] = {
		['name'] = 'Pontiac Firebird',
		['brand'] = 'Pontiac',
		['model'] = 'firebird',
		['price'] = 93000,
		['category'] = 'muscle',
		['hash'] = `firebird`,
		['shop'] = 'pdm',
	},
	['gsxb'] = {
		['name'] = 'Buick GSX',
		['brand'] = 'Buick',
		['model'] = 'gsxb',
		['price'] = 7000,
		['category'] = 'muscle',
		['hash'] = `gsxb`,
		['shop'] = 'pdm',
	},

	
	--- Off-Road
	['bfinjection'] = {
		['name'] = 'Bf Injection',
		['brand'] = 'Annis',
		['price'] = 9000,
		['category'] = 'offroad',
		['model'] = 'bfinjection',
		['hash'] = `bfinjection`,
		['shop'] = 'pdm',
	},
	['picador'] = {
		['name'] = 'Chevrolet El Camino',
		['brand'] = 'Chevrolet',
		['price'] = 22000,
		['category'] = 'offroad',
		['model'] = 'picador',
		['hash'] = `picador`,
		['shop'] = 'pdm',
	},
	['lifted86k10'] = {
		['name'] = 'Chevy Lifted K10 Crew Cab',
		['brand'] = 'Chevy',
		['price'] = 18000,
		['category'] = 'offroad',
		['model'] = 'lifted86k10',
		['hash'] = `lifted86k10`,
		['shop'] = 'pdm',
	},
	['sdgmc'] = {
		['name'] = 'GMC Yukon Denali Pickup',
		['brand'] = 'GMC',
		['model'] = 'sdgmc',
		['price'] = 65000,
		['category'] = 'offroad',
		['hash'] = `sdgmc`,
		['shop'] = 'pdm',
	},
	['k5blazer'] = {
		['name'] = 'Chevrolet K5 Blazer',
		['brand'] = 'Chevrolet',
		['model'] = 'k5blazer',
		['price'] = 15000,
		['category'] = 'offroad',
		['hash'] = `k5blazer`,
		['shop'] = 'pdm',
	},
	['ramsrt10'] = {
		['name'] = 'Dodge Ram SRT10 2006',
		['brand'] = 'Dodge',
		['model'] = 'ramsrt10',
		['price'] = 49000,
		['category'] = 'offroad',
		['hash'] = `ramsrt10`,
		['shop'] = 'pdm',
	},
	['superdutyk'] = {
		['name'] = 'Ford F350 Lifted',
		['brand'] = 'Ford',
		['model'] = 'superdutyk',
		['price'] = 35000,
		['category'] = 'offroad',
		['hash'] = `superdutyk`,
		['shop'] = 'pdm',
	},
	['c10custom'] = {
		['name'] = 'Chevy C10 Stepside',
		['brand'] = 'Chevrolet',
		['model'] = 'c10custom',
		['price'] = 30000,
		['category'] = 'offroad',
		['hash'] = `c10custom`,
		['shop'] = 'pdm',
	},
	['f150'] = {
		['name'] = '2013 Ford F150 Raptor',
		['brand'] = 'Ford',
		['model'] = 'f150',
		['price'] = 48035,
		['category'] = 'offroad',
		['hash'] = `f150`,
		['shop'] = 'pdm',
	},
	['nissantitan17'] = {
		['name'] = '2021 Nissan Titan',
		['brand'] = 'Nissan',
		['model'] = 'nissantitan17',
		['price'] = 75945,
		['category'] = 'offroad',
		['hash'] = `nissantitan17`,
		['shop'] = 'pdm',
	},
	['silv86'] = {
		['name'] = '1987 Silverado on Rims',
		['brand'] = 'Chevrolet',
		['model'] = 'silv86',
		['price'] = 12000,
		['category'] = 'offroad',
		['hash'] = `silv86`,
		['shop'] = 'pdm',
	},
	['nm_19ram'] = {
		['name'] = '2019 Dodge Ram on Rims',
		['brand'] = 'Dodge',
		['model'] = 'nm_19ram',
		['price'] = 66050,
		['category'] = 'offroad',
		['hash'] = `nm_19ram`,
		['shop'] = 'pdm',
	},


	
	--- SUVs
	
	['bjxl'] = {
		['name'] = 'BeeJay XL',
		['brand'] = 'Karin',
		['model'] = 'bjxl',
		['price'] = 19000,
		['category'] = 'suvs',
		['hash'] = `bjxl`,
		['shop'] = 'pdm',
	},
	['g5502019'] = {
		['name'] = 'Mercedes G Class G550 2019',
		['brand'] = 'Mercedes',
		['model'] = 'g5502019',
		['price'] = 150000,
		['category'] = 'suvs',
		['hash'] = `g5502019`,
		['shop'] = 'pdm',
	},
	['trhawk'] = {
		['name'] = '2018 Jeep Grand Cherokee TH',
		['brand'] = 'Jeep',
		['model'] = 'trhawk',
		['price'] = 98700,
		['category'] = 'suvs',
		['hash'] = `trhawk`,
		['shop'] = 'pdm',
	},
	['x5e53'] = {
		['name'] = '2006 BMW X5 SUV',
		['brand'] = 'BMW',
		['model'] = 'x5e53',
		['price'] = 30000,
		['category'] = 'suvs',
		['hash'] = `x5e53`,
		['shop'] = 'pdm',
	},
	['wildtrak'] = {
		['name'] = '2021 Bronco Wildtrak',
		['brand'] = 'Ford',
		['model'] = 'wildtrak',
		['price'] = 49850,
		['category'] = 'suvs',
		['hash'] = `wildtrak`,
		['shop'] = 'pdm',
	},
	['tahoe'] = {
		['name'] = '2014 Chevrolet Tahoe',
		['brand'] = 'Chevrolet',
		['model'] = 'tahoe',
		['price'] = 19000,
		['category'] = 'suvs',
		['hash'] = `tahoe`,
		['shop'] = 'pdm',
	},
	['fx4'] = {
		['name'] = '2006 Land Rover Discovery',
		['brand'] = 'Land Rover',
		['model'] = 'fx4',
		['price'] = 19000,
		['category'] = 'suvs',
		['hash'] = `fx4`,
		['shop'] = 'pdm',
	},
	['fj40'] = {
		['name'] = '1960s Toyota Land Cruiser',
		['brand'] = 'Toyota',
		['model'] = 'fj40',
		['price'] = 3000,
		['category'] = 'suvs',
		['hash'] = `fj40`,
		['shop'] = 'pdm',
	},
	['urus2018'] = {
		['name'] = '2018 Lamborghini Urus',
		['brand'] = 'Lamborghini',
		['model'] = 'urus2018',
		['price'] = 218009,
		['category'] = 'suvs',
		['hash'] = `urus2018`,
		['shop'] = 'pdm',
	},
	--- Sedans
	['asea'] = {
		['name'] = 'Asea',
		['brand'] = 'Declasse',
		['model'] = 'asea',
		['price'] = 2500,
		['category'] = 'sedans',
		['hash'] = `asea`,
		['shop'] = 'pdm',
	},
	['96impala'] = {
		['name'] = 'Chevrolet Impala SS 1996',
		['brand'] = 'Chevrolet',
		['model'] = '96impala',
		['price'] = 8000,
		['category'] = 'sedans',
		['hash'] = `96impala`,
		['shop'] = 'pdm',
	},
	['belair57'] = {
		['name'] = 'Chevrolet Bel Air 1957',
		['brand'] = 'Chevrolet',
		['model'] = 'belair57',
		['price'] = 6000,
		['category'] = 'sedans',
		['hash'] = `belair57`,
		['shop'] = 'pdm',
	},
	['celebrity82'] = {
		['name'] = 'Chevrolet Celebrity 1982',
		['brand'] = 'Chevrolet',
		['model'] = 'celebrity82',
		['price'] = 3000,
		['category'] = 'sedans',
		['hash'] = `celebrity82`,
		['shop'] = 'pdm',
	},
	['85impalar'] = {
		['name'] = 'Chevrolet Impala 1985 Rusted',
		['brand'] = 'Chevrolet',
		['model'] = '85impalar',
		['price'] = 2000,
		['category'] = 'sedans',
		['hash'] = `85impalar`,
		['shop'] = 'pdm',
	},
	['85impala'] = {
		['name'] = 'Chevrolet Impala 1985',
		['brand'] = 'Chevrolet',
		['model'] = '85impala',
		['price'] = 3000,
		['category'] = 'sedans',
		['hash'] = `85impala`,
		['shop'] = 'pdm',
	},
	['rrphantom'] = {
		['name'] = 'Rolls Royce Phantom 2018',
		['brand'] = 'Rolls',
		['model'] = 'rrphantom',
		['price'] = 475000,
		['category'] = 'sedans',
		['hash'] = `rrphantom`,
		['shop'] = 'pdm',
	},
	['subwrx'] = {
		['name'] = 'Subaru Impreza WRX 2004',
		['brand'] = 'Subaru',
		['model'] = 'subwrx',
		['price'] = 40000,
		['category'] = 'sedans',
		['hash'] = `subwrx`,
		['shop'] = 'pdm',
	},
	['w221s63'] = {
		['name'] = 'Mercedes S63 AMG Sedan',
		['brand'] = 'Mercedes',
		['model'] = 'w221s63',
		['price'] = 90000,
		['category'] = 'sedans',
		['hash'] = `w221s63`,
		['shop'] = 'pdm',
	},
	['300srt8'] = {
		['name'] = 'Chrysler 300 SRT8',
		['brand'] = 'Chrysler',
		['model'] = '300srt8',
		['price'] = 55000,
		['category'] = 'sedans',
		['hash'] = `300srt8`,
		['shop'] = 'pdm',
	},
	['honci4'] = {
		['name'] = '2018 Honda Civic',
		['brand'] = 'Honda',
		['model'] = 'honci4',
		['price'] = 34500,
		['category'] = 'sedans',
		['hash'] = `honci4`,
		['shop'] = 'pdm',
	},
	['civic'] = {
		['name'] = '1999 Honda Civic',
		['brand'] = 'Honda',
		['model'] = 'civic',
		['price'] = 4500,
		['category'] = 'sedans',
		['hash'] = `civic`,
		['shop'] = 'pdm',
	},


	
	--- Sports
	['alpha'] = {
		['name'] = 'Alpha',
		['brand'] = 'Albany',
		['model'] = 'alpha',
		['price'] = 53000,
		['category'] = 'sports',
		['hash'] = `alpha`,
		['shop'] = 'pdm',
	},
	['r82012'] = {
		['name'] = 'R8 Plus 2012',
		['brand'] = 'Audi',
		['model'] = 'r82012',
		['price'] = 150000,
		['category'] = 'sports',
		['hash'] = `r82012`,
		['shop'] = 'pdm',
	},
	['a80'] = {
		['name'] = 'Toyota Supra',
		['brand'] = 'Toyota',
		['model'] = 'a80',
		['price'] = 49000,
		['category'] = 'sports',
		['hash'] = `a80`,
		['shop'] = 'pdm',
	},
	['gtr'] = {
		['name'] = '2019 Nissan GTR',
		['brand'] = 'Nissan',
		['model'] = 'gtr',
		['price'] = 91000,
		['category'] = 'sports',
		['hash'] = `gtr`,
		['shop'] = 'pdm',
	},
	['rmodmartin'] = {
		['name'] = 'Aston Martin DBS Superleggera',
		['brand'] = 'Aston',
		['model'] = 'rmodmartin',
		['price'] = 316000,
		['category'] = 'super',
		['hash'] = `rmodmartin`,
		['shop'] = 'pdm',
	},
	['rmodrs6'] = {
		['name'] = '2020 Audi RS6 C8',
		['brand'] = 'Audi',
		['model'] = 'rmodrs6',
		['price'] = 116000,
		['category'] = 'sports',
		['hash'] = `rmodrs6`,
		['shop'] = 'pdm',
	},
	['rmodgtr50'] = {
		['name'] = 'Nissan GTR50',
		['brand'] = 'Nissan',
		['model'] = 'rmodgtr50',
		['price'] = 113540,
		['category'] = 'sports',
		['hash'] = `rmodgtr50`,
		['shop'] = 'pdm',
	},
	['rmodm8gte'] = {
		['name'] = 'BMW M8 GTE',
		['brand'] = 'BMW',
		['model'] = 'rmodm8gte',
		['price'] = 121315,
		['category'] = 'sports',
		['hash'] = `rmodm8gte`,
		['shop'] = 'pdm',
	},
	['m2'] = {
		['name'] = '2019 BMW M2',
		['brand'] = 'BMW',
		['model'] = 'm2',
		['price'] = 58900,
		['category'] = 'sports',
		['hash'] = `m2`,
		['shop'] = 'pdm',
	},
	['bmwm3e92'] = {
		['name'] = '2016 BMW M3',
		['brand'] = 'BMW',
		['model'] = 'bmwm3e92',
		['price'] = 65000,
		['category'] = 'sports',
		['hash'] = `bmwm3e92`,
		['shop'] = 'pdm',
	},
	['f82duke'] = {
		['name'] = '2019 BMW M4 F82',
		['brand'] = 'BMW',
		['model'] = 'f82duke',
		['price'] = 74500,
		['category'] = 'sports',
		['hash'] = `f82duke`,
		['shop'] = 'pdm',
	},
	['f82lw'] = {
		['name'] = '2019 BMW M4 LW',
		['brand'] = 'BMW',
		['model'] = 'f82lw',
		['price'] = 77500,
		['category'] = 'sports',
		['hash'] = `f82lw`,
		['shop'] = 'pdm',
	},
	['cats'] = {
		['name'] = '2016 Cadillac CTS-V',
		['brand'] = 'Cadillac',
		['model'] = 'cats',
		['price'] = 77500,
		['category'] = 'sports',
		['hash'] = `cats`,
		['shop'] = 'pdm',
	},
	
	--- Sports Classic
	['ardent'] = {
		['name'] = 'Ardent',
		['brand'] = 'Ocelot',
		['model'] = 'ardent',
		['price'] = 30000,
		['category'] = 'sportsclassics',
		['hash'] = `ardent`,
		['shop'] = 'pdm',
	},
	
	--- Super
	['adder'] = {
		['name'] = 'Adder',
		['brand'] = 'Truffade',
		['model'] = 'adder',
		['price'] = 280000,
		['category'] = 'super',
		['hash'] = `adder`,
		['shop'] = 'luxury',
	},
	['911gt3rs'] = {
		['name'] = 'Porsche 911GT3RS',
		['brand'] = 'Porsche',
		['model'] = '911gt3rs',
		['price'] = 161100,
		['category'] = 'super',
		['hash'] = `911gt3rs`,
		['shop'] = 'luxury',
	},
	['c8daytona'] = {
		['name'] = 'Chevrolet C8 Daytona',
		['brand'] = 'Chevrolet',
		['model'] = 'c8daytona',
		['price'] = 150599,
		['category'] = 'super',
		['hash'] = `c8daytona`,
		['shop'] = 'luxury',
	},
	['rmodbacalar'] = {
		['name'] = 'Bentley Bacalar',
		['brand'] = 'Bentley',
		['model'] = 'rmodbacalar',
		['price'] = 750000,
		['category'] = 'super',
		['hash'] = `rmodbacalar`,
		['shop'] = 'luxury',
	},
	['rmodbentleygt'] = {
		['name'] = 'Bentley Continental GT',
		['brand'] = 'Bentley',
		['model'] = 'rmodbentleygt',
		['price'] = 217850,
		['category'] = 'super',
		['hash'] = `rmodbentleygt`,
		['shop'] = 'luxury',
	},
	['rmodchiron300'] = {
		['name'] = 'Bugatti Chiron SuperSport300',
		['brand'] = 'Bugatti',
		['model'] = 'rmodchiron300',
		['price'] = 1200000,
		['category'] = 'super',
		['hash'] = `rmodchiron300`,
		['shop'] = 'luxury',
	},
	['gt17'] = {
		['name'] = '2021 Ford GT',
		['brand'] = 'Ford',
		['model'] = 'gt17',
		['price'] = 500000,
		['category'] = 'super',
		['hash'] = `gt17`,
		['shop'] = 'luxury',
	},
	['diablo'] = {
		['name'] = 'Lamborghini Diablo',
		['brand'] = 'Lamborghini',
		['model'] = 'diablo',
		['price'] = 162000,
		['category'] = 'super',
		['hash'] = `diablo`,
		['shop'] = 'luxury',
	},
	['lp610'] = {
		['name'] = 'Lamborghini Huracan',
		['brand'] = 'Lamborghini',
		['model'] = 'lp610',
		['price'] = 1000000,
		['category'] = 'super',
		['hash'] = `lp610`,
		['shop'] = 'luxury',
	},

	-- Vans
	['bison'] = {
		['name'] = 'Bison',
		['brand'] = 'Bravado',
		['model'] = 'bison',
		['price'] = 18000,
		['category'] = 'vans',
		['hash'] = `bison`,
		['shop'] = 'pdm',
	},
	['mule'] = {
		['name'] = '2016 Chevrolet Uhaul',
		['brand'] = 'Chevrolet',
		['model'] = 'mule',
		['price'] = 9000,
		['category'] = 'vans',
		['hash'] = `mule`,
		['shop'] = 'pdm',
	},
	
	-- Utility
	['sadler'] = {
		['name'] = 'Sadler',
		['brand'] = 'Vapid',
		['model'] = 'sadler',
		['price'] = 20000,
		['category'] = 'offroad',
		['hash'] = `sadler`,
		['shop'] = 'pdm',
	},
	
}
